name: ai_camera
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  # ffmpeg_kit_flutter_min_gpl: ^5.1.0
  path_provider: ^2.1.3
  gallery_saver: ^2.3.2
  image: ^4.5.4
  permission_handler: ^11.0.1
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  photo_view: ^0.14.0
  android_intent_plus: 5.1.0
  open_file_plus: ^3.4.1+1
  native_device_orientation: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  rename: ^3.1.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/
    - assets/

# Native Splash Screen Configuration
flutter_native_splash:
  color: "#000000"
  color_dark: "#000000"
  
  # Use the generated splash screen logo
  image: assets/logo.png
  
  # Branding (optional bottom image)
  # branding: assets/branding.png
  
  android_12:
    color: "#000000"
    image: assets/logo.png
    
  android: true
  ios: false
  web: false
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Path to your logo
  min_sdk_android: 21 # Recommended for modern Android